# Generated by Django 4.1.7 on 2023-03-27 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('role', models.CharField(max_length=50)),
                ('is_online', models.BooleanField(default=False)),
                ('phone_number', models.CharField(default='test', max_length=50)),
                ('job_locatin', models.CharField(default='test', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Permission_level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Permission_level', models.IntegerField(default=1)),
                ('profile_from', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile1', to='accounts.profile')),
                ('profile_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile2', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='accounts.profile')),
            ],
        ),
     
    ]
