# Generated by Django 4.1.7 on 2023-03-27 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='accepted',
        ),
    ]
