# Generated by Django 4.1.7 on 2023-04-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_friend_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='job_locatin',
            new_name='job_location',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(default='test', max_length=50),
        ),
    ]
