# Generated by Django 4.1.7 on 2023-04-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_job_locatin_profile_job_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
