# Generated by Django 4.1.7 on 2023-04-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='test', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='hobbies_location',
            field=models.CharField(default='test', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='studies_location',
            field=models.CharField(default='test', max_length=150),
        ),
    ]
