# Generated by Django 4.1.7 on 2023-04-03 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_bio_profile_hobbies_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='job_location',
            field=models.CharField(default='test', max_length=150),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fields', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('visible_to', models.ManyToManyField(related_name='visible_groups', to='accounts.profile')),
            ],
        ),
    ]
