# Generated by Django 4.1.7 on 2023-04-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_job_location_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='fields',
            field=models.TextField(default=''),
        ),
    ]
