# Generated by Django 4.1.7 on 2023-04-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_verify',
        ),
        migrations.AddField(
            model_name='alert',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='house_location',
            field=models.CharField(default='test', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='step',
            field=models.CharField(blank=True, default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='Permission_level',
        ),
    ]
